### ISSUE TITLE
To-Do List (master) [01/03]

### ISSUE THREAD

**Issue by krasCGQ** [krasCGQ/build-tools-gcc#3]
## What To Do?

- [x] Fix build issues with GCC 5 and below
  - [x] With older version of Glibc (2.27) for GCC 5 and Linaro GCC 4.9
- [x] Restore GCC 4.9.4 build support
  - [x] With older version of Glibc (2.26)
  - [x] With older version of Binutils (2.29.1; no link issues)
- [x] Fix `<pthread.h>` missing headers for both `i686` ~~and `x86_64`~~ target~~s~~ (can't really be helped)
- [x] Fetch an external patch from buildroot to fix GCC 4.9's `libsanitizer` compilation error for ARM/i686 targets
- [x] Fix Linux headers installation issue for `i686` target
- [x] Workaround GCC 6+ compilation due to 'undeclared' `PATH_MAX`
- [x] Hard reset GCC `git` source before checking out
- [x] Update Linux to 5.0
- [x] Switch GNU-A 8 to git version
- [x] Don't build GCC 5 and lower for x86_64 target due to unresolvable error
- [x] Cleanup for code of conduct criteria
- [x] Submit everything to upstream as a PR

## Status

GCC version | ARM | ARM64 | i686 | x86_64
:-: | :-: | :-: | :-: | :-:
**GNU 4.9.4** | S/S | S/S | S/S | F/F
**Linaro 4.9** | S/S | S/S | S/S | F/F
**GNU 5.5.0** | S/S | S/~~F~~S | S/S | F/F
**Linaro 5.5** | S/S | S/S | S/S | ?^/F
**GNU 6.5.0** | S/S | S/S | S/S | S/S
**Linaro 6.5** | S/S | S/S | ~~F~~S/S | S/S
**GNU 7.4.x** | S/S | S/S | S/S | S/S
**Linaro 7.4** | S/S | S/S | S/S | S/S
**GNU 8.3.x** | S/S | S/S | S/S | S/S
**Linaro 8.2/3** | S/S | S/S | S/S | S/S
**GNU 9.0.1** | -/S | -/S | -/S | -/S

(S)uccess; (F)ail; - N/A; ?^ Not tested, but most likely will fail

## Tested On

OS: Arch Linux `x86_64`
Kernel: Linux-VK `4.20.13-1` / `4.20.14-1`
Compiler: `gcc version 8.2.1 20181121 (GCC)`

**Comment by krasCGQ** [comment]
Merged with commit USBhost/build-tools-gcc@4f169e05.
